### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by tstanisl** [tstanisl/ctest#2]
- [x] keep single node list in `ctest`, add status field
- [ ] add escaped to filter
- [ ] add negated pattern to filter
- [x] add "else" branch to EXCEPT and ASSERT
- [x] remove non-ctest arguments form commnad line options
- [x] add seed to `--ctest_shuffle`
- [x] disable coloring for non-term output
- [ ] optionally run all/selected tests within `fork()`
- [x] support for fixtures
